### ISSUE TITLE
(I-2) Add snowball entity

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#100]
Create a custom snowball entity. This may be done best using the custom entity library @estebanfer made.

- Snowballs turn into rocks when causing damage to something (confirm how this works in HD)
- All procedurally generated rocks at the beginning of a snowing level need to be replaced with snowballs.

**Comment by erictran4011** [comment]
https://github.com/SuperNinjaFat/HDmod/pull/145
