### ISSUE TITLE
(I-1) Revise the Mammoth enemy

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#103]
The current mammoth enemy is very close to being accurate, but there are still a few issues.

- Because it uses the Lamassu as the base entity, UFOs target it and damaging it causes it to be launched into the air. Replace the base entity with something that fixes these issues and brings it to be accurate to its HD counterpart.

**Comment by erictran4011** [comment]
https://github.com/SuperNinjaFat/HDmod/pull/118
