### ISSUE TITLE
Improve acid damage mechanic

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#110]
In HD, the pits of acid when exploring the inside of The Worm level have a mechanic that damages you over time while submerged. The current implementation of this mechanic in our mod is bad. Fix it.

The current implementation will poison the player when submerged in acid over the span of several seconds.
Here's what I don't like about it and what I think should be done to improve it:

- The current implementation I believe only effects player 1. This needs to be extended to affect not only all other players but all enemies with the exception of the worm babies, critter maggots, and the bacterium as it did in HD.
- How it should work is that a timer is associated with each entity upon being submerged, is increased for every frame while it's still submerged, and is removed upon resurfacing.
- It's hard to tell that the acid is going to poison you. It would be nice to have some way to telegraph to the player that being submerged in the acid is a bad thing. By gradually increasing a color (white?) on the entity during that time I think would work well. A similar effect is done for the timer on shotgun monkeys in the mod "Monkey Hell" by @estebanfer .

**Comment by estebanfer** [comment]
If we add the effect to show the player about damage in acid, I think it would also be fair to add something to warn when an acid bubble is going to spawn from the acid to prevent getting poisoned randomly when trying to get in the acid. Maybe add some small bubble effects, like boiling, when a bubble is about to spawn
