### ISSUE TITLE
Improve debugging methods

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#112]
The debugging methods currently are a MESS. Here's what's wrong with them:

- They can't be saved. The options should be loaded from a table from the save file the same way the randomizer 2 does it https://github.com/spelunky-fyi/overlunky/blob/01647a818cf1f7975f4359976a92f57633cd560d/examples/randomizer2.lua
- Some options aren't even implemented and should be commented out or straight-up removed.
- The overall format of the options needs to be formatted in a way that's not confusing. Options that the average player will want to change and the debug options should be separated.

**Comment by SuperNinjaFat** [comment]
Could we have a checkbox option for enabling debugging mode? Debugging mode would either show all debugging methods in the options menu or may even display its own separate menu.

**Comment by SuperNinjaFat** [comment]
The custom entities we've been making usually have their own spawning and debugging methods. As new entities have been added, "spawn entity" options have shown up in the main options menu. These should be organized to be less of a mess.

**Comment by estebanfer** [comment]
Yeah I think that it would be nice to add a "show debug menu" button/checkbox, that shows a separate ImGui window

**Comment by SuperNinjaFat** [comment]
Feeling debugging could be useful
