### ISSUE TITLE
Fix tree growable vine platform issue

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#114]
S2 level generation currently adds vines to some tree branches. When a vine is placed overlapping a branch, that branch will allow the player to pass through it.
Image of the issue: https://media.discordapp.net/attachments/960666216018616320/1007399209315614882/unknown.png
@estebanfer has suggested a way to fix this:
> Yeah you remove the vine and then get the branch probably by using get_entities_overlapping_hitbox or get_entities_at, then move it to the same position it is already, using move_grid_entity should update the grid

**Comment by estebanfer** [comment]
Sooo should this be closed?

**Comment by SuperNinjaFat** [comment]
> Sooo should this be closed?

Yes, thank you
