### ISSUE TITLE
Improve worm baby AI

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#176]
I've noticed some inconsistencies with the worm baby AI. They don't seem to work well around regenerating walls, and they lack the behavior from HD where if they fall partially onto a 1 width tile, they'll attempt to move onto it and stay facing one direction on that tile.

**Comment by estebanfer** [comment]
I can copy most of the alien tank moving behavior to the baby worm for the moving to center behavior, it would also fix the regenerating walls issue since that code also checks for activefloor

**Comment by SuperNinjaFat** [comment]
Good idea

**Comment by estebanfer** [comment]
Also, in hd, they don't seem to change of direction when touching a wall on air, on the current implementation they do
