### ISSUE TITLE
Replace s2 generated dark level torches

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#181]
Due to us using script-based level generation, several entities that dark level torches would normally take into consideration are spawned over. For instance, dark level torches can spawn in liquids and over exit doors.

Prevent torches from procedurally spawning and spawn them in via script to avoid these issues.

**Comment by estebanfer** [comment]
I might assign this to myself tomorrow, unless anyone wants to do this before.
Also, wall torches spawn one per path room (excluding entrance room) in S2 and HD

**Comment by SuperNinjaFat** [comment]
Sounds good to me
