### ISSUE TITLE
Improve piranha enemy

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#210]
Could use some sound effects. The flying fish in S2 make "swishing" sound effects when moving through water, maybe we could make them have that as well?

Piranhas also still attack players when they are dead.

**Comment by estebanfer** [comment]
uhh what swishing sound effects from fish? I don't hear any when they're on water

**Comment by SuperNinjaFat** [comment]
Oh you're right, I don't hear any sounds from them now. I think I was hearing sounds from humphead

**Comment by estebanfer** [comment]
so should a sound be added or not?

**Comment by SuperNinjaFat** [comment]
> so should a sound be added or not?
Not now. But I think a later update needs an issue to review all enemies to re-evaluate their sounds, effects and balancing

**Comment by SuperNinjaFat** [comment]
So I think just fixing it attacking dead players will be fine
