### ISSUE TITLE
Add gray shaded versions of COG doors and crush trap textures

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#230]

**Comment by SuperNinjaFat** [comment]
Since this one's its own task, it's probably a good idea to keep it open until a PR is made that includes these additions

**Comment by greeniporcini** [comment]
ooooooookay, assumed that closing it just signified that the task is done

**Comment by SuperNinjaFat** [comment]
Just made a PR that will add both of these textures but will only implement the crush trap. I've left a note in the COG entrance implementation issue to implement it there.
