### ISSUE TITLE
Add Yama head gib texture

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#232]
I just noticed that in HD, Yama's head has special gibs.

**Comment by greeniporcini** [comment]
going to provide gibs for other spelunky 2 entities

- [ ] Green knight
- [ ] Scorpionfly
- [ ] Snail
- [ ] Mammoth

**Comment by SuperNinjaFat** [comment]
Added in with this https://github.com/SuperNinjaFat/HDmod/pull/288
