### ISSUE TITLE
Fix scorpionfly bugs

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#282]
The scorpionfly switches its base entity between a few entities in order to achieve its behaviors.
Some issues have been occurring with this system:

- Sometimes the mosquito entity isn't removed upon death of the other entities, leaving a buzzing sound in the air
- When agroed in its winged state and pressing up against a wall, its mosquito entity sometimes agros and "sticks" into the wall
- The scepter shot can target one of them, which results in the scepter shot appearing to be stuck to an invisible entity.

**Comment by SuperNinjaFat** [comment]
@erictran4011 Just a heads up

**Comment by erictran4011** [comment]
I believe problems 1 and 3 would be solved by making sure that the hidden entities are properly destroyed when the scorpionfly is. As for problem 2, this is probably because the chase code is custom written and the minimal speed cap is too low.

**Comment by SuperNinjaFat** [comment]
Flying scorpionflies do not trigger arrow traps
