### ISSUE TITLE
Redo COG entrance spawn

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#283]
The City of Gold entrance door still uses the S2 implementation. The following needs to be done in order to achieve its HD counterpart:

- Prevent non-scripted creation of the COG door entities
- Implement a COG procedural spawn.
I'm pretty sure HD's COG entrance can spawn in any room and requires 1-tile high clearance. Verify if this is true.
Obviously it can't spawn in liquids
- Make a COG library for creating the COG entrance with an optional gray textured version for the stone temple option

**Comment by estebanfer** [comment]
![image](https://github.com/SuperNinjaFat/HDmod/assets/20376110/089413f8-cf7f-4ba2-af1d-75c1bd7454b8)
For rooms it seems to only check that it's on path, and not on entrace or exit
and only requires empty space there with a floor below

**Comment by SuperNinjaFat** [comment]
> ![image](https://user-images.githubusercontent.com/20376110/271399529-089413f8-cf7f-4ba2-af1d-75c1bd7454b8.png) For rooms it seems to only check that it's on path, and not on entrace or exit and only requires empty space there with a floor below

Nice, that's what I suspected!

**Comment by estebanfer** [comment]
it's fine it spawning it below floor even when it's 2 floors tall now, right?

**Comment by SuperNinjaFat** [comment]
> it's fine it spawning it below floor even when it's 2 floors tall now, right?

Yes I think it's fine. If anything, we'd change this in a future update to support mounts.

**Comment by SuperNinjaFat** [comment]
For whoever does this, see if you can fix/prevent this as well
![image](https://github.com/SuperNinjaFat/HDmod/assets/35533648/9ba97f11-b815-425f-a92c-4d874687c139)

**Comment by estebanfer** [comment]
Do you remember what's the order the COG door spawns on HD?
In S2 it seems to spawn before traps

**Comment by SuperNinjaFat** [comment]
> Do you remember what's the order the COG door spawns on HD? In S2 it seems to spawn before or same time as traps

![image](https://github.com/SuperNinjaFat/HDmod/assets/35533648/84d0854a-7244-47df-85c1-03a01c4383be)

**Comment by SuperNinjaFat** [comment]
The code above is the `manage_spawnchance_enemies` method
```c
manage_spawnchance_tiki_tombstone();
manage_spawnchance_arrowtrap();
manage_spawnchance_crushtrap();
manage_spawnchance_pushblock_powderkeg();
manage_spawnchance_spikeball();
manage_spawnchance_common();//rocks, gold, skeletons, gold key & locked chest, damsels, succubus
manage_spawnchance_enemies();//enemies
```

**Comment by SuperNinjaFat** [comment]
> ![image](https://user-images.githubusercontent.com/20376110/271399529-089413f8-cf7f-4ba2-af1d-75c1bd7454b8.png) For rooms it seems to only check that it's on path, and not on entrace or exit and only requires empty space there with a floor below

Actually I think I'm wrong, I don't think I actually found the COG spawn in the code above.

**Comment by estebanfer** [comment]
I checked again, it's in `manage_spawnchance_enemies()`, along with other extra spawns like Anubis, worm entrance.
Should spawn even after all the enemies spawned, though I guess enemies don't affect it
