### ISSUE TITLE
Add shopkeeper outposts

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#301]
Add shopkeeper outposts with the option to disable them. They should use the same rules as S2.

> After murdering 5-8 Shopkeepers (or obtaining the sin equivalent), the Shopkeeper's Association begin establishing posse rooms, made of wood containing 2-4 shopkeepers.

> Posse rooms always spawn along the main path to the exit door, and may not only spawn in all standard levels, but may also appear levels like The City of Gold. They never spawn in levels that cannot contain an angry shopkeeper at the exit door.

**Comment by estebanfer** [comment]
Closed by #406
