### ISSUE TITLE
Improve Anubis spawn validation method

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#410]
Anubis can spawn directly inside pushblocks and other things that frag him instantly. This happens too often to ignore! Improve his spawn validation code to avoid those kinds of entities.

**Comment by estebanfer** [comment]
Should also be forced to spawn on path as discussed before right?
https://discord.com/channels/849697383608877066/849701051791835157/1117631914275246100

**Comment by SuperNinjaFat** [comment]
> Should also be forced to spawn on path as discussed before right? https://discord.com/channels/849697383608877066/849701051791835157/1117631914275246100

Sure, let's try it. I was under the impression we didn't agree on it, but worst comes to worst we can take it out if it hurts gameplay

**Comment by estebanfer** [comment]
alright!
