### ISSUE TITLE
Revise procedural trap spawning

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#429]
Procedural trap spawning currently uses the api method to spawn monsters. Revise trap spawning to use the theme hook for post traps instead.
An example dregu provided:
```lua
state.current_theme:set_post_spawn_traps(function()
  local ax, ay, bx, by = get_bounds()
  for y=ay-0.5,by+0.5,-1 do
    for x=ax+0.5,bx-0.5,1 do
      if position_is_valid(x, y, LAYER.FRONT, POS_TYPE.FLOOR | POS_TYPE.SAFE) and prng:random_chance(20, PRNG_CLASS.PROCEDURAL_SPAWNS) then
        spawn_on_floor(ENT_TYPE.MONS_FISH, x, y, LAYER.FRONT)
      end
    end
  end
end)
```
Be careful to preserve trap spawn order.

**Comment by estebanfer** [comment]
uhh, I did this in #454, but I didn't think about trap spawn order 😅 
What does it mean? What should determine the order?

**Comment by SuperNinjaFat** [comment]
> uhh, I did this in #454, but I didn't think about trap spawn order 😅 What does it mean? What should determine the order?

This should be fine since we're still using the prodecural definitions set in the lvl files. Thanks for asking

**Comment by estebanfer** [comment]
what does the spawn order mean anyway? If it's like, arrow traps spawning before pushblocks, because of the order of definition of the files, it wouldn't be taken into account, only the chances

**Comment by SuperNinjaFat** [comment]
> what does the spawn order mean anyway? If it's like, arrow traps spawning before pushblocks, because of the order of definition of the files, it wouldn't be taken into account, only the chances

Oh, really? Now I'm not sure if I understand what determines the order.

Malacath explained it to me once in this message: 
https://discord.com/channels/150366712775180288/802954429996990515/901369393672507402
> For your own registered chances the order is the same as the order you registered them in.

So would that mean spawn order is determined by the order `define_procedural_spawn`s are set?

Here's the order of hd's procedural spawn methods:
```c
manage_spawnchance_tiki_tombstone();
manage_spawnchance_arrowtrap();
manage_spawnchance_crushtrap();
manage_spawnchance_pushblock_powderkeg();
manage_spawnchance_spikeball();
manage_spawnchance_common();//rocks, gold, skeletons, gold key & locked chest, damsels, succubus
manage_spawnchance_enemies();//enemies
```

**Comment by estebanfer** [comment]
I guess yeah, though since now we handle trap spawns by ourselves, it would be up to the script to handle the order
Still should apply for the other procedural spawns tho

**Comment by estebanfer** [comment]
currently I loop through a table with `pairs` for the trap spawns, which wouldn't guarantee any specific order

**Comment by SuperNinjaFat** [comment]
> currently I loop through a table with `pairs` for the trap spawns, which wouldn't guarantee any specific order

Gotcha.
