### ISSUE TITLE
Fix ending recap history

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#435]
Currently, ending an olmec run shows that you only left from Tiamat in the recap, regardless of the actual run history. Fix this so it successfully preserves run data.

**Comment by estebanfer** [comment]
uh, I'm not having that issue, was that fixed?
I guess an issue would be that mothership is shown as a separate section there but not worm
Also, killing an alienlord makes the progress journal to show anubis as killed

**Comment by SuperNinjaFat** [comment]
Yeah I might be wrong regarding Tiamat always showing up, I think making sure the sections show up correctly and the enemy icons in the progress journal would be what need changed.

**Comment by estebanfer** [comment]
should worm and mothership show up in journal as separate sections or should they not?

**Comment by SuperNinjaFat** [comment]
Yeah, maybe there's a graphic we can make to better portray the shortcut? Something like an arrow looping back onto itself?
Ooooo, what if one of the artists made the graphic like a serpant, maybe inspired from real world map serpents https://cdn.mos.cms.futurecdn.net/wthgcgFiaoLsHkCxVn5oS8.jpg

**Comment by estebanfer** [comment]
sounds nice
