### ISSUE TITLE
Revise worm tongue

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#88]
The worm tongue could use a revision to be more accurate to its HD counterpart.
Currently:
- The particle effects spawned upon the worm emerging aren't as pronounced as HD's. Add more and have them flung further.
- The radius that the blocks are destroyed in upon the worm emerging is too small.
- The animation of the mouth opening is done too quickly, making it only possible to see the fully closed and fully open frames.
- The rumbling sound and effect is done by creating a boulder spawner and destroying it before the boulder spawns. This needs to be replaced with a rumbling sound effect and an explosion sound effect played when the worm emerges, and using a screen shaking effect using the existing API method.
- There are no jiggle physics applied to the tongue when objects interact with it. A possible physics equation to use for these interaction might be harmonic osillation with resistive force: https://math.libretexts.org/Bookshelves/Calculus/Book%3A_Calculus_(OpenStax)/17%3A_Second-Order_Differential_Equations/17.03%3A_Applications_of_Second-Order_Differential_Equations
- Objects held and backpacks worn by players are still visible upon being swallowed by the worm.

**Comment by SuperNinjaFat** [comment]
This is a much needed improvement, though imo there's still room for improvement

**Comment by estebanfer** [comment]
Is this good to close now?

**Comment by SuperNinjaFat** [comment]
> Is this good to close now?

Yep!
