### ISSUE TITLE
Fix 1-4 exit door sounds and critters

### ISSUE THREAD

**Issue by SuperNinjaFat** [SuperNinjaFat/HDmod#96]
S2's retail campaign has 2 exit doors. One door leads to Volcana and the other leads to the Jungle. A soundscape is played that increases in volume when in proximity to and 3 of the corresponding critters are spawned around these exit doors.

Currently HDmod's 1-4 has one of these door's effects applied to it depending on which side of the level the door was placed. What needs to be done:

- Remove the soundscape and critters from the 1-4 exit door or in the campaign that don't match the relevant theme.
- Add 3 relevant critters and soundscapes to the exit door at the end of each world.

**Comment by SuperNinjaFat** [comment]
The S2 exit door critters now no longer show up (for me, at least).

**Comment by estebanfer** [comment]
> The S2 exit door critters now no longer show up (for me, at least).

[Yeah🔽](https://github.com/SuperNinjaFat/HDmod/blob/173a7912360a5b20af9783b2b1821fb9ddb841bb/lib/gen/touchups.lua#LL226C1-L245C2)
```lua
-- remove nonscript critters
set_pre_entity_spawn(function(ent_type, x, y, l, overlay, spawn_flags)
    if spawn_flags & SPAWN_TYPE.SCRIPT == 0 then
        return spawn_entity(ENT_TYPE.FX_SHADOW, x, y, l, 0, 0)
    end
end,
	SPAWN_TYPE.ANY,-- SPAWN_TYPE.LEVEL_GEN_GENERAL | SPAWN_TYPE.LEVEL_GEN_PROCEDURAL,
	0,
	ENT_TYPE.MONS_CRITTERANCHOVY,
	ENT_TYPE.MONS_CRITTERBUTTERFLY,
	ENT_TYPE.MONS_CRITTERCRAB,
	ENT_TYPE.MONS_CRITTERDRONE,
	ENT_TYPE.MONS_CRITTERDUNGBEETLE,
	ENT_TYPE.MONS_CRITTERFIREFLY,
	ENT_TYPE.MONS_CRITTERFISH,
	ENT_TYPE.MONS_CRITTERLOCUST,
	ENT_TYPE.MONS_CRITTERPENGUIN,
	ENT_TYPE.MONS_CRITTERSLIME,
	ENT_TYPE.MONS_CRITTERSNAIL
)
```

**Comment by estebanfer** [comment]
> * Remove the soundscape and critters from the 1-4 exit door or in the campaign that don't match the relevant theme.

What do you mean with "campaign"? The camp?

**Comment by SuperNinjaFat** [comment]
I was just about to reword that, sorry if that's confusing. Yes, by campaign I mean any other doors in our Mod that might have unintentional soundscapes applied to them by the game's code, like what happened here.

**Comment by SuperNinjaFat** [comment]
And now that I think about it, do we even need to spawn 3 critters at the exit doors of each world? I don't think HD does it, and S2 seems to only do it in a few places. What fo you think?

**Comment by SuperNinjaFat** [comment]
I think the soundscapes, if easy to implement, makes sense and would be cool

**Comment by estebanfer** [comment]
> And now that I think about it, do we even need to spawn 3 critters at the exit doors of each world? I don't think HD does it, and S2 seems to only do it in a few places. What do you think?

I think it only happens in S2 when there are different paths, so you can distinguish between the 2 different levels you can go (jungle and volcana, tidepool and temple). And doesn't seem to happen in HD. So maybe it's better to not include the critters.
And I've already implemented the soundscape for level 1-4. I think ice caves and olmec don't have one

**Comment by SuperNinjaFat** [comment]
I agree, let's leave them out then.
And if some places like olmec or ice caves don't have soundscapes then it's okay to leave them without them.

**Comment by estebanfer** [comment]
Also the temple door ambient sound is barely noticeable

**Comment by SuperNinjaFat** [comment]
So did you find a way to use the sound entities that the game used for S2 1-4? And if so, would that lower the volume of the ice caves music to make the temple door ambient sound more noticeable?
